name: opendap_working
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - contextily
  - rasterio
  - scipy
  - cartopy
  - openblas==0.2.19
  - requests
  - bs4
  - beautifulsoup4
  - pip

